### PR TITLE
Entity adapter - property description

### PR DESCRIPTION
**Pull request by peku22**
Hi everyone,
I came across this issue, that I can't add a description to a response field when generating the OpenAPI using the Entity adapter. So I created this little modification, which allows adding a description to the entities' properties. 

Example:
```
/**
 * @description Alpha-2 code (e.g. 'CZ')
 */
public string $country;
```

So far, only single-line descriptions are possible.

### CODE REVIEW

**Comment by f3l1x** [comment]
Hi @peku22. Thank you. We will release v0.7 without this change, but I like the way you can add description, I will take a look at solution.

**Comment by miranovy** [comment]
Hi, how to create multiline description? Thank you

**Comment by peku22** [comment]
Hi there, well, it's not possible (so far). It would require adjusting the parseAnnotationDescription method to process all the subsequent rows, like until there is @ at the beginnig of the row. Do you want me to try to implement that?

**Comment by f3l1x** [comment]
Hi @miranovy @peku22, can you please take a look at all-in-one repository https://github.com/contributte/apitte and implement this kind of feature there? I'm going to sunset this repository split.

**Pull request closed without merging**
